rdodin:
  name: Roman Dodin
  description: SR Linux PLM
  avatar: https://avatars.githubusercontent.com/u/5679861

jbemmel:
  name: Jeroen van Bemmel
  description: Webscale Architect
  avatar: https://avatars.githubusercontent.com/u/2031627

sogawa:
  name: Satoshi Ogawa
  description: Webscale Solutions Architect
  avatar: https://avatars.githubusercontent.com/u/2031627

azyablov:
  name: Anton Zyablov
  description: Lead Solution Architect
  avatar: https://avatars.githubusercontent.com/u/22647209

amitk:
  name: Amit K
  description: Consulting Engineer
  avatar: https://gitlab.com/rdodin/pics/-/wikis/uploads/6e635cf946b54f33d7d314143ad4144d/image.png

mau:
  name: Mauricio Rojas
  description: Network Automation Consulting Engineer
  avatar: https://avatars.githubusercontent.com/u/69992138

wdesmedt:
  name: Walter De Smedt
  description: Consulting engineer
  avatar: https://avatars.githubusercontent.com/u/13483865
